### ISSUE TITLE
Set code conventions

### ISSUE THREAD

**Issue by jaketae** [bigscience-workshop/evaluation#43]
As the repository gets larger, we will eventually need to decide on a code convention. Though preferences may vary, it's probably safe to stick to the setup in `transformers`, which is [`black` + `isort`](https://github.com/huggingface/transformers/blob/bfc885091b38a0d418acc31e6d8847684ba6981b/Makefile#L59).

We could create a simplified `Makefile` and do something like

```make
.PHONY: style

style:
	black .
	isort . --profile=black .
``` 

Alternatively, create a `.pre-commit-config.yaml`.

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: 21.7b0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/isort
    rev: 5.9.3
    hooks:
      - id: isort
        args: ["--profile", "black"]
```
